parameters:
#    d_lauritz_jeopardy_main.example.class: DLauritz\Jeopardy\MainBundle\Example

services:
#    d_lauritz_jeopardy_main.example:
#        class: %d_lauritz_jeopardy_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
