parameters:
#    d_lauritz_jeopardy_game.example.class: DLauritz\Jeopardy\GameBundle\Example

services:
#    d_lauritz_jeopardy_game.example:
#        class: %d_lauritz_jeopardy_game.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
